In [35]:
import numpy as np

# Test matrix
scores = np.array([[85, 90, 78], 
                [92, 88, 86],])

blocked_mask = [0, 0, 1]

# Show the shape of the matrix
print(scores.shape)

(2, 3)


In [36]:
# transpose of a matrix
print(np.swapaxes(scores, -1, -2))
print(np.transpose(scores))
# The original scores matrix is unchanged
print(scores.shape)

[[85 92]
 [90 88]
 [78 86]]
[[85 92]
 [90 88]
 [78 86]]
(2, 3)


In [56]:
# numeric functions
print(np.sqrt(scores))
print(np.sqrt(scores.shape[-1]))

print(np.max(scores, axis=-1, keepdims=True))
print(np.max(scores, axis=0, keepdims=True))
print(np.max(scores))

print(np.exp(scores))

print(np.sum(np.exp(scores), axis=-1, keepdims=True))
print(np.sum(scores, axis=0, keepdims=True))

[[9.21954446 9.48683298 8.83176087]
 [9.59166305 9.38083152 9.2736185 ]]
1.7320508075688772
[[90]
 [92]]
[[92 90 86]]
92
[[8.22301271e+36 1.22040329e+39 7.49841700e+33]
 [9.01762841e+39 1.65163625e+38 2.23524660e+37]]
[[1.22863381e+39]
 [9.20514450e+39]]
[[177 178 164]]


In [37]:
# Turn into numpy array
blocked_mask = np.asarray(blocked_mask, dtype=bool)
print (blocked_mask)

[False False  True]


In [38]:
# broadcast the mask to the shape of the scores matrix
blocked_mask = np.broadcast_to(blocked_mask, scores.shape)
print(blocked_mask)

[[False False  True]
 [False False  True]]


In [50]:
# Boolean functions
# All true or not, starting with the last axes (col in this case)
print(np.all(blocked_mask, axis=-1))
# starting with the first axes (row in this case)
print(np.all(blocked_mask, axis=0))

# Any true or not, starting with the last axes (col in this case)
print(np.any(blocked_mask, axis=-1))
# starting with the first axes (row in this case)
print(np.any(blocked_mask, axis=0))

# Can group
print(np.any(np.all(blocked_mask, axis=-1)))
print(np.any(np.all(blocked_mask, axis=0)))

[False False]
[False False  True]
[ True  True]
[False False  True]
False
True


In [51]:
# Conditional value setting
print(np.where(blocked_mask, -np.inf, scores))

[[ 85.  90. -inf]
 [ 92.  88. -inf]]
